# Generated by Django 2.0.10 on 2019-02-17 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
                ('skill', models.CharField(max_length=300)),
                ('file', models.FileField(upload_to='uploads/cv/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='CvCatagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobCircular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('post_name', models.CharField(blank=True, max_length=50)),
                ('publication_Date', models.DateTimeField(auto_now=True)),
                ('job_type', models.CharField(choices=[('d', 'Digital marketing'), ('g', 'Game Devolopment'), ('w', 'Web Development'), ('d', 'Data analysist')], max_length=1)),
                ('qualification', models.CharField(choices=[('s', 'SSC'), ('h', 'HHS'), ('H', 'Hns')], max_length=1)),
                ('skill', models.CharField(max_length=150)),
                ('website', models.URLField(blank=True, max_length=400)),
                ('age_limit', models.SmallIntegerField(blank=True)),
                ('job_nature', models.CharField(choices=[('f', 'Full Time'), ('p', 'Part Time')], max_length=1)),
                ('application_last_date', models.DateTimeField(auto_now_add=True)),
                ('salary_range', models.CharField(choices=[('10', '10-15'), ('15', '15-20'), ('20', '20-25'), ('25', '25-30'), ('30', '30-35'), ('35', '35-40'), ('40', '40-45'), ('45', '45-50'), ('50', '50-55'), ('55', '55-60'), ('60', '60-65'), ('65', '65-70'), ('n', 'Negoriable')], max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cv',
            name='catagory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobcv.CvCatagory'),
        ),
        migrations.AddField(
            model_name='cv',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
