# Generated by Django 2.0.13 on 2019-02-18 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcv', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cvcatagory',
            options={'ordering': ('name',), 'verbose_name': 'catagory', 'verbose_name_plural': 'catagories'},
        ),
        migrations.AlterField(
            model_name='jobcircular',
            name='application_last_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='jobcircular',
            name='publication_Date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='jobcircular',
            name='salary_range',
            field=models.CharField(choices=[('10', '10-15'), ('15', '15-20'), ('20', '20-25'), ('25', '25-30'), ('30', '30-35'), ('35', '35-40'), ('40', '40-45'), ('45', '45-50'), ('50', '50-55'), ('55', '55-60'), ('60', '60-65'), ('65', '65-70'), ('n', 'Negoriable')], max_length=2),
        ),
    ]
