# Generated by Django 2.0.13 on 2019-02-18 17:18

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jobcv', '0002_auto_20190218_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='approve',
            field=models.CharField(choices=[('a', 'approve'), ('d', 'deny')], default=django.utils.timezone.now, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobcircular',
            name='approve',
            field=models.CharField(choices=[('a', 'approve'), ('d', 'deny')], default=datetime.datetime(2019, 2, 18, 17, 18, 52, 9700, tzinfo=utc), max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobcircular',
            name='job_nature',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='jobcircular',
            name='job_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jobcircular',
            name='publication_Date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='jobcircular',
            name='qualification',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='jobcircular',
            name='salary_range',
            field=models.CharField(max_length=10),
        ),
    ]
