# Generated by Django 2.0.13 on 2019-02-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcv', '0003_auto_20190218_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='approve',
            field=models.CharField(choices=[('a', 'approve'), ('d', 'deny')], default='d', max_length=1),
        ),
        migrations.AlterField(
            model_name='jobcircular',
            name='approve',
            field=models.CharField(choices=[('a', 'approve'), ('d', 'deny')], default='d', max_length=1),
        ),
    ]
