# Generated by Django 2.0.10 on 2019-02-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcv', '0005_auto_20190220_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcircular',
            name='age_limit',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='jobcircular',
            name='application_last_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
