# Generated by Django 2.0.13 on 2019-03-27 04:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobcv', '0007_auto_20190222_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='image',
            field=models.FileField(default=django.utils.timezone.now, upload_to='profile/'),
            preserve_default=False,
        ),
    ]
