# Generated by Django 2.0.10 on 2019-02-22 08:22

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0005_auto_20190221_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='github',
            field=models.URLField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='skill',
            field=models.CharField(default=datetime.datetime(2019, 2, 22, 8, 22, 36, 176646, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
