# Generated by Django 2.0.10 on 2019-02-22 09:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0007_auto_20190222_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='work_inside',
            field=models.CharField(default=datetime.datetime(2019, 2, 22, 9, 1, 48, 929854, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
    ]
