# Generated by Django 2.0.10 on 2019-02-22 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0008_profile_work_inside'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='work_inside',
            new_name='working',
        ),
    ]
